grgsm_livemon: Disable PPS sync
Because of the following error when used with USRP B100

[INFO] [MULTI_USRP]     1) catch time transition at pps edge
Traceback (most recent call last):
  File "./grgsm_livemon.py", line 365, in <module>
    main()
  File "./grgsm_livemon.py", line 343, in main
    tb = top_block_cls(fc=options.fc, gain=options.gain, osr=options.osr, ppm=options.ppm, samp_rate=options.samp_rate, shiftoff=options.shiftoff)
  File "./grgsm_livemon.py", line 114, in __init__
    self.rtlsdr_source_0.set_time_unknown_pps(osmosdr.time_spec_t())
  File "/home/vasko/gr38/lib/python3.7/dist-packages/osmosdr/osmosdr_swig.py", line 2543, in set_time_unknown_pps
    return _osmosdr_swig.source_sptr_set_time_unknown_pps(self, time_spec)
RuntimeError: RuntimeError: Board 0 may not be getting a PPS signal!
No PPS detected within the time interval.
See the application notes for your device.

Change-Id: Iee6124bdb2441666a53ac9ee5239894aea61dfde